services:
  postgres:
    image: pgvector/pgvector:0.8.2-pg17-trixie
    container_name: fs-learn-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fs_learn
    ports:
      - "9999:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
